name: Shell Script

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run shell script
        run: sh ./shell-script.sh
        
      - name: create directory
        run: sh ./createdirectory.sh
